#
# Copyright (c) 2023 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Publish osdpctl

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'osdpctl-v*'

jobs:
  publish:
    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      with:
        toolchain: stable
        override: true
    - name: "Setup environment - trigger"
      if: github.ref == 'refs/heads/master'
      run: echo "TAG=${TRIGGER_TAG}" >> "${GITHUB_ENV}"
      env:
        TRIGGER_TAG: ${{ github.event.inputs.tag }}
    - name: "Setup environment - tag"
      if: github.ref != 'refs/heads/master'
      run: echo "TAG=${REL_TAG}" >> "${GITHUB_ENV}"
      env:
        REL_TAG: ${{ github.ref_name }}
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2
      with:
        package: osdpctl
    - name: "Publish crate"
      run: |
        cargo publish --token ${CRATES_TOKEN} -p osdpctl
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
